### ISSUE TITLE
Provide internet access to non-students

### ISSUE THREAD

**Issue by britter** [nix-community-bochum/nix-learning-group#22]
I've been at the past two meet ups and both time people were tinkering with the network setup at the meeting room. Unfortunately without success. In order to provide internet access for non-students at the end somebody shared their eduroam account. The situation frustrates me because I can't work on my machine until somebody shares their eduroam account.

Given that fact that we've tried to fix this adhoc two times without success, I feel like we should explore options upfront to be better prepared for the next meetup. On the way out Malte mentioned there's an event WLAN that can be booked somehow via RUB. Maybe that's a solution?

**Comment by libnewton** [comment]
Hi, I've talked to the IT administration of the Uni and they'll fix the LAN ports for next time. Then hooking our router will work and we have a RUB-login-free wifi.

**Comment by britter** [comment]
Okay, can we maybe try that a few days before the meet up to make sure it works? 😇

**Comment by libnewton** [comment]
I'll try

**Comment by libnewton** [comment]
I confirmed this issue is now fixed and at least the port where we hooked our router the 2nd meeting will definitly work.
